# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Qwen3 Coder
    provider: openai
    apiBase: https://integrate.api.nvidia.com/v1
    model: qwen/qwen3-coder-480b-a35b-instruct
    apiKey: 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
    requestOptions:
      timeout: 50000
